/**
 * Copy the icons the site uses from Tabler Icons (MIT, https://tabler.io/icons)
 * into src/components/icons.generated.ts, so the build ships only these few
 * dozen and not all 5,000. Add a name to NAMES and run `npm run icons`.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const dir = join(root, 'node_modules/@tabler/icons/icons/outline');

const NAMES = [
  // Games
  'user-search', 'soccer-field', 'arrows-up-down', 'coins', 'arrows-exchange', 'robot', 'tag',
  // Navigation and pages
  'home', 'dots', 'trophy', 'chart-line', 'users', 'book-2', 'settings', 'ball-football',
  // In the games
  'trending-up', 'trending-down', 'sparkles', 'dice-5', 'bulb', 'camera', 'refresh', 'info-circle', 'arrow-left',
  // Budget XI themes and season badges
  'arrow-big-up-lines', 'scale', 'stars', 'crown', 'diamond', 'target-arrow', 'star', 'shield-check', 'flame',
  // Price Tag verdicts, Road chemistry, errors
  'thumb-up', 'mood-smile', 'mood-neutral', 'mood-sad', 'link', 'alert-triangle',
  // Share sheet
  'share', 'download', 'copy', 'x',
];

const icons = {};
for (const name of NAMES) {
  const svg = readFileSync(join(dir, `${name}.svg`), 'utf8');
  // Keep the shapes; drop Tabler's invisible 24×24 bounding-box path and the whitespace.
  icons[name] = [...svg.matchAll(/<(path|circle|rect|line|polyline|polygon|ellipse)\b[^>]*\/>/g)]
    .map((m) => m[0].replace(/\s+/g, ' ').replace(' />', '/>'))
    .filter((el) => !el.includes('stroke="none"'))
    .join('');
}

const out = `/* Generated by pipeline/icons.mjs from Tabler Icons (MIT License,
 * Copyright (c) 2020-2026 Paweł Kuna, https://tabler.io/icons). Do not edit. */

export const ICONS = ${JSON.stringify(icons, null, 2)} as const;

export type IconName = keyof typeof ICONS;
`;
writeFileSync(join(root, 'src/components/icons.generated.ts'), out);
console.log(`src/components/icons.generated.ts: ${NAMES.length} icons`);
